const data={
    products:[
        {
            _id:"1",
            name:"Romas Women’s Rayon Regular",
            category:"kurtis",
            image:'./images/w1.jpg',
            price:499,
            brand:'Genric',
            rating:4,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"2",
            name:"Ethnic Dress",
            category:"kurtis",
            image:'./images/w2.jpg',
            price:530,
            brand:'Janasya',
            rating:4.5,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"3",
            name:"Cotton Regular Kurti",
            category:"kurtis",
            image:'./images/w3.jpg',
            price:499,
            brand:'Myx',
            rating:5,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"4",
            name:"Rayon Printed Kurta",
            category:"kurtis",
            image:'./images/w4.jpg',
            price:599,
            brand:'Banas',
            rating:4,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"5",
            name:"Women Kurti",
            category:"kurtis",
            image:'./images/w5.jpg',
            price:409,
            brand:'Myx',
            rating:4,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"6",
            name:"Regular Kurti",
            category:"kurtis",
            image:'./images/w6.jpg',
            price:700,
            brand:'Banas',
            rating:4,
            numsReviews:10,
            description:'high quality product',
        },
        {
            _id:"7",
            name:"Cotton Regular Kurti",
            category:"kurtis",
            image:'./images/w7.jpg',
            price:499,
            brand:'Genric',
            rating:4,
            numsReviews:10,
            description:'high quality product',
        }
    ]
}
export default data;